# Generated by Django 4.2.16 on 2024-10-08 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0002_remove_borrowing_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing',
            name='member',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='books_app.member'),
        ),
    ]
